project:
  name: go-invoice
  binary: go-invoice
  module: github.com/mrz1836/go-invoice
  main: ./cmd/go-invoice/main.go

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
    - "-X main.buildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./cmd/go-invoice"
