package schemas

const (
	keyDescription          = "description"
	keyExamples             = "examples"
	keyFormat               = "format"
	keyDefault              = "default"
	keyEnum                 = "enum"
	keyAdditionalProperties = "additionalProperties"
	keyEmail                = "email"
	keyClientID             = "client_id"
	keyClientName           = "client_name"
	keyInvoiceID            = "invoice_id"
	keyHours                = "hours"
	keyRate                 = "rate"
	keyObject               = "object"
	keyProperties           = "properties"
	keyName                 = "name"
	keyMinLength            = "minLength"
	keyMaxLength            = "maxLength"
	keyRequired             = "required"
	keyMinimum              = "minimum"
	keyMaximum              = "maximum"
	keyType                 = "type"
	typeBoolean             = "boolean"
	typeArray               = "array"
	typeString              = "string"
	typeNumber              = "number"
	typeJSON                = "json"
	formatDate              = "date"
	exampleInvoiceID        = "INV-001"
)
